### ISSUE TITLE
ElasticsearchLogShipper has the wrong success criteria for Bulk operations

### ISSUE THREAD

**Issue by jarlelin** [jarlelin/serilog-sinks-elasticsearch#1]
When reading from a durable file and uploading bulk actions to the elastic search server, the log shipper checks the HTTP response for a Success Code and if true it writes the bookmarks and moves on. 

Likewise we have had an issue where a document does successfully write to the index, but for some (haven't figured out how yet) reason the response code does not indicate success. This leads to the log shipper continiously writing the same document to the index multiple times.

This is the relevant code that seems to be wrong: (starting at line 179 in ElasticsearchLogShipper.cs)

```
if (count > 0)
{
 var response = _state.Client.Bulk(payload);

 if (response.Success)
 {
    WriteBookmark(bookmark, nextLineBeginsAtOffset, currentFilePath);
 }
 else
 {
     SelfLog.WriteLine("Received failed ElasticSearch shipping result {0}: {1}", response.HttpStatusCode, response.OriginalException);
}
}
```

The bulk operation returns success indicators in the body of the result, and this is what should be checked for success status.

**Comment by jarlelin** [comment]
@mivano Sorry about assigning you to this repo if you don't want to. I couldn't find a way to create an issue or asking a question in any other meaningful way. 

Could you please comment on the issue described above?

**Comment by mivano** [comment]
it is a bit hidden, but the sinks are still using the issue tracker of Serilog (https://github.com/serilog/serilog/issues). I would advise you to place your question there for discoverability and more knowledge to get an answer for it.

**Comment by jarlelin** [comment]
Thanks.
